import './rightBar.scss';

const RightBar = () => {
    return (
        <div className='rightBar'>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
            <div>RightBar</div>
        </div>
    )
}

export default RightBar;